import { invoke } from '@tauri-apps/api/core';
import type * as T from './types';

export const getConnection = () => invoke<T.ConnectInfo | null>('get_connection');
export const listNotes = () => invoke<T.NoteDto[]>('list_notes');
export const getNote = (id: string) => invoke<T.NoteDto>('get_note', { id });
export const createNote = (title: string, category: string) => invoke<T.NoteDto>('create_note', { title, category });
export const updateNote = (id: string, title: string, content: string, category: string) => invoke<T.NoteDto>('update_note', { id, title, content, category });
export const deleteNote = (id: string) => invoke<void>('delete_note', { id });
export const listChecklists = () => invoke<T.ChecklistDto[]>('list_checklists');
export const getChecklist = (id: string) => invoke<T.ChecklistDto>('get_checklist', { id });
export const createChecklist = (title: string, category: string) => invoke<T.ChecklistDto>('create_checklist', { title, category });
export const updateChecklist = (id: string, title: string, category: string) => invoke<T.ChecklistDto>('update_checklist', { id, title, category });
export const deleteChecklist = (id: string) => invoke<void>('delete_checklist', { id });
export const addItem = (checklistId: string, text: string, parentLocalId: string | null) => invoke<T.ItemDto>('add_item', { checklistId, text, parentLocalId });
export const setItemText = (checklistId: string, itemLocalId: string, text: string) => invoke<void>('set_item_text', { checklistId, itemLocalId, text });
export const setItemChecked = (checklistId: string, itemLocalId: string, checked: boolean) => invoke<void>('set_item_checked', { checklistId, itemLocalId, checked });
export const deleteItem = (checklistId: string, itemLocalId: string) => invoke<void>('delete_item', { checklistId, itemLocalId });
export const reorderItems = (checklistId: string, orderedTopLevelIds: string[]) => invoke<void>('reorder_items', { checklistId, orderedTopLevelIds });
export const listCategories = () => invoke<T.CategoriesDto>('list_categories');
export const search = (query: string) => invoke<T.SearchResultsDto>('search', { query });
export const triggerSync = () => invoke<unknown>('trigger_sync');
export const syncStatus = () => invoke<T.SyncStatusDto>('sync_status');
export const listConflicts = () => invoke<T.ConflictDto[]>('list_conflicts');
export const resolveConflict = (seq: number, keep: 'mine' | 'server') => invoke<void>('resolve_conflict', { seq, keep });
export const connectInstance = (url: string, apiKey: string) => invoke<T.ConnectInfo>('connect_instance', { url, apiKey });
export const disconnectInstance = () => invoke<void>('disconnect_instance');
export const getSettings = () => invoke<{ instanceUrl: string | null; syncIntervalMinutes: number }>('get_settings');
export const setSyncInterval = (minutes: number) => invoke<void>('set_sync_interval', { minutes });
export const checkUpdate = () => invoke<T.UpdateInfo>('check_update');
export const downloadUpdate = (url: string) => invoke<string>('download_update', { url });
export const installUpdate = (path: string) => invoke<void>('install_update', { path });
export const restartApp = () => invoke<void>('restart_app');
